daily_expense_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracker.urls', namespace='tracker')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

expense_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from expense_tracker.settings import ADMIN_ROUTE


urlpatterns = [
    path(ADMIN_ROUTE, admin.site.urls),
    path('', include('tracker.urls', namespace='tracker')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tracker/urls.py
from django.urls import path

from tracker import views

app_name = 'tracker'

urlpatterns = [
    path('', views.PurchaseListView.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('items/', views.ItemListView.as_view(), name='items'),
    path('item/new/', views.ItemCreateView.as_view(), name='item-new'),
    path('item/<int:pk>', views.ItemDetailView.as_view(), name='item-detail'),
    path('item/<int:pk>/delete/', views.ItemDeleteView.as_view(), name='item-delete'),
    path('item/<int:pk>/update/', views.ItemUpdateView.as_view(), name='item-update'),
    path('purchase/<int:pk>', views.PurchaseDetailView.as_view(), name='purchase-detail'),
    path('purchase/new/', views.PurchaseCreateView.as_view(), name='purchase-new'),
    path('purchase/<int:pk>/update/', views.PurchaseUpdateView.as_view(), name='purchase-update'),
    path('purchase/<int:pk>/delete/', views.PurchaseDeleteView.as_view(), name='purchase-delete'),
]

tracker/models.py
from django.db import models
from django.urls import reverse
from django.db.models import Sum

from PIL import Image

class Item(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.FloatField()
    img = models.ImageField(default='default.jpg', upload_to='items')

    def __str__(self):
        return f'Item: {self.name}'

    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)

    #     img = Image.open(self.img.path)
    #     if img.height > 300 or img.width > 300:
    #         output_size = (300, 300)
    #         img.thumbnail(output_size)
    #         img.save(self.img.path)
    
    def get_absolute_url(self):
        return reverse('tracker:item-detail', kwargs={'pk' : self.pk})


class Purchase(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    date_purchased = models.DateField()
    purchase_amount = models.FloatField(default=0)

    def __str__(self):
        return f'Purchase: {self.id}'

    def get_absolute_url(self):
        return reverse('tracker:purchase-detail', kwargs={'pk' : self.pk})

    @staticmethod
    def total():
        total = Purchase.objects.aggregate(Sum('purchase_amount'))
        return total['purchase_amount__sum']

    def save(self):
        self.purchase_amount = self.item.price * self.quantity
        super().save()

tracker/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.forms.widgets import SelectDateWidget
# from django.http import HttpResponse

from tracker.models import Item, Purchase

# def home(request):
#     return render(request, 'tracker/home.html')

def about(request):
    return render(request, 'tracker/about.html', {'title': 'About'})


class PurchaseListView(ListView):
    model = Purchase
    template_name = 'tracker/home.html'
    context_object_name = 'purchases'
    ordering = ['-date_purchased']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total'] = Purchase.total()
        return context


class PurchaseDetailView(DetailView):
    model = Purchase
    context_object_name = 'purchase'


class PurchaseCreateView(CreateView):
    model = Purchase
    fields = ['item', 'quantity', 'date_purchased']

    def get_form(self):
        form = super().get_form()
        form.fields['date_purchased'].widget = SelectDateWidget(
            years=range(2000, 2051), 
            empty_label=
            ['--- Choose Year ---', '--- Choose Month ---', '--- Choose Day ---']
        )
        form.fields['date_purchased'].widget.attrs = {'style': 'width: 30%; display: inline-block; margin-right: 2%;'}
        return form


class PurchaseUpdateView(UpdateView):
    model = Purchase
    fields = ['item', 'quantity', 'date_purchased']

    def get_form(self):
        form = super().get_form()
        form.fields['date_purchased'].widget = SelectDateWidget(
            years=range(2000, 2051), 
            empty_label=
            ['--- Choose Year ---', '--- Choose Month ---', '--- Choose Day ---']
        )
        form.fields['date_purchased'].widget.attrs = {'style': 'width: 30%; display: inline-block; margin-right: 2%;'}
        return form


class PurchaseDeleteView(DeleteView):
    model = Purchase
    success_url = '/'


class ItemListView(ListView):
    model = Item
    template_name = 'tracker/items.html'
    context_object_name = 'items'
    ordering = ['price']


class ItemDetailView(DetailView):
    model = Item
    context_object_name = 'item'


class ItemCreateView(CreateView):
    model = Item
    fields = ['name', 'price', 'description','img']


class ItemUpdateView(UpdateView):
    model = Item
    fields = ['name', 'price', 'description','img']


class ItemDeleteView(DeleteView):
    model = Item
    success_url = '/items/'

tracker/templates/tracker/about.html
{% extends 'tracker/base.html' %}
{% load static %}

{% block body %}
    <div class="my-5">
        <div class="row">
            <div class="col-md-6">
                <img src="{% static 'tracker/images/expenses.svg' %}" 
                style="max-width: 100%; border-radius: 10px;"/>
            </div>
            <div class="col-md-6 d-flex flex-column justify-content-center align-items-center">
                <h3 class="text-dark">About Expense Tracker</h3>
                <h5 class="text-secondary text-justify">
                    It is a simple app that runs in your browser helping you manage your expenses. 
                    It is for personal use and best used for your daily purchases.
                </h5>
            </div>
        </div>
    </div>
{% endblock %}

tracker/templates/tracker/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'tracker/images/favicon.ico' %}" />

    <title>
        {% if title %}
            Expense Tracker - {{ title }}
        {% else %}
            Expense Tracker
        {% endif %}
    </title>

    <script src="https://kit.fontawesome.com/e327786071.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'tracker:home' %}">
            <img src="{% static 'tracker/images/logo.png' %}" width="30" height="30" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <style>
              .active-link{
                border-bottom: 2px solid rgb(214, 61, 61);
              }

              .nav-item:not(.active-link):hover {
                border-bottom: 2px solid rgb(94, 34, 204);
              }
            </style>
            {% with request.resolver_match.url_name as url_name %}
              <li class="nav-item ml-2 {% if url_name == 'home' %}active active-link{% endif %}">
                <a class="nav-link" href="{% url 'tracker:home' %}">Home </a>
              </li>
              <li class="nav-item ml-2 {% if url_name == 'items' %}active active-link{% endif %}">
                <a class="nav-link" href="{% url 'tracker:items' %}">Items</a>
              </li>
              <li class="nav-item ml-2 {% if url_name == 'about' %}active active-link{% endif %}">
                  <a class="nav-link" href="{% url 'tracker:about' %}">About</a>
              </li>
            {% endwith %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
        {% block body %}{% endblock %}
        
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </div>
</body>
</html>

tracker/templates/tracker/home.html
{% extends 'tracker/base.html' %}

{% block body %}
    <nav aria-label="breadcrumb" class="my-3">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">Purchases</li>
        </ol>
    </nav>

    <div class="my-3">
        <div class="row">
            <div class="col-md-6"></div>

            <div class="col-md-6">
                <a class="btn btn-success float-right mb-3" href="{% url 'tracker:purchase-new' %}">
                    <i class="fas fa-plus"></i>
                    Add New
                </a>
            </div>
        </div>
        
        <table class="table table-hover table-dark">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Item</th>
                <th scope="col">Date</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
                {% if purchases %}
                    {% for purchase in purchases %}
                        <tr>
                            <th scope="row">
                                <a href="{% url 'tracker:purchase-detail' purchase.id %}">
                                    {{ forloop.counter }}
                                </a>
                            </th>
                            <td>
                                <a href="{% url 'tracker:item-detail' purchase.item.id %}">
                                    {{ purchase.item.name }}
                                </a>
                            </td>
                            <td>{{ purchase.date_purchased | date:'D F d, Y' }}</td>
                            <td>{{ purchase.quantity }}</td>
                            <td>Rs. {{ purchase.purchase_amount | floatformat:'2' }}</td>
                            <td>
                                <a href="{% url 'tracker:purchase-update' purchase.id %}">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a href="{% url 'tracker:purchase-delete' purchase.id %}">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="5" class="float-center">Grand Total</td>
                        <td>Rs. {{ total | floatformat:'2' }}</td>
                    </tr>
                {% else %}
                    <tr><td colspan="6">You've made no purchases yet!</td></tr>
                {% endif %}
            </tbody>
        </table>
    </div>
{% endblock %}

tracker/templates/tracker/item_confirm_delete.html
{% extends "tracker/base.html" %}

{% block body %}
    <div class="my-3">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Item</legend>
                <h2>Are you sure you want to delete the item "{{ object.name }}"?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'tracker:item-detail' object.id %}">Back to Safety!</a>
            </div>
        </form>
    </div>
{% endblock body %}

tracker/templates/tracker/item_detail.html
{% extends 'tracker/base.html' %}

{% block body %}
    <nav aria-label="breadcrumb" class="my-3">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'tracker:items' %}">Items</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ item.name.title }}</li>
        </ol>
    </nav>

    <div class="card my-3" style="max-width: 540px;">
        <div class="row no-gutters">
        <div class="col-md-4">
            <img src="{{ item.img.url }}" class="card-img" alt="Item Image">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">
                    {{ item.name }}
                </h5>
                <p class="card-text">{{ item.description }}</p>
                <p class="card-text"><small class="text-muted">Rate: Rs. {{ item.price | floatformat:'2' }}</small></p>
                
                <a href="{% url 'tracker:item-update' item.id %}">
                    <i class="fas fa-edit"></i>
                </a>
                |
                <a href="{% url 'tracker:item-delete' item.id %}">
                    <i class="fas fa-trash"></i>
                </a>
            </div>
        </div>
        </div>
    </div>
{% endblock %}

tracker/templates/tracker/item_form.html
{% extends "tracker/base.html" %}
{% load crispy_forms_tags %}

{% block body %}
    <nav aria-label="breadcrumb" class="my-3">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'tracker:items' %}">Items</a></li>
            <li class="breadcrumb-item active" aria-current="page">Create New Item</li>
        </ol>
    </nav>

    <div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class = "border-bottom mb-4">Add Item</legend>
                {{ form | crispy }}
            </fieldset>
            <div class = "form-group">
                <button class = "btn btn-success" type = "submit">Update</button>
            </div>
        </form>
    </div>
{% endblock body %}

tracker/templates/tracker/items.html
{% extends 'tracker/base.html' %}

{% block body %}
    <nav aria-label="breadcrumb" class="my-3">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">Items</li>
        </ol>
    </nav>

    <div class="row">
        <div class="col-md-6"></div>
        <div class="my-3 col-md-6">
            <a class="btn btn-success float-right" href="{% url 'tracker:item-new' %}">
                <i class="fas fa-plus"></i>
                Add New
            </a>
        </div>
    </div>

    <div class="row">
        {% for item in items %}
            <div class="card col-md-6 mb-3" style="max-width: 540px;">
                <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="{{ item.img.url }}" class="card-img" alt="Item Image">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="{% url 'tracker:item-detail' item.id %}">
                                {{ item.name }}
                            </a>
                        </h5>
                        <p class="card-text">
                            {% if item.description|length|get_digit:"-1" <= 20 %}
                                {{ item.description }}
                            {% else %}
                                {{ item.description | slice:20 }} ...
                            {% endif %}
                        </p>
                        <p class="card-text"><small class="text-muted">Rate: Rs. {{ item.price | floatformat:'2' }}</small></p>
                        
                        <a href="{% url 'tracker:item-update' item.id %}">
                            <i class="fas fa-edit"></i>
                        </a>
                        |
                        <a href="{% url 'tracker:item-delete' item.id %}">
                            <i class="fas fa-trash"></i>
                        </a>
                    </div>
                </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

tracker/templates/tracker/purchase_confirm_delete.html
{% extends "tracker/base.html" %}

{% block body %}
    <div class="my-3">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Purchase</legend>
                <h2>Are you sure you want to delete the purchase "{{ object.item.name }} on {{ purchase.date_purchased }}"?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'tracker:purchase-detail' object.id %}">Back to Safety!</a>
            </div>
        </form>
    </div>
{% endblock body %}

tracker/templates/tracker/purchase_detail.html
{% extends 'tracker/base.html' %}

{% block body %}
    <nav aria-label="breadcrumb" class="my-3">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'tracker:home' %}">Purchases</a></li>
            <li class="breadcrumb-item active" aria-current="page">Purchase of {{ purchase.item.name }} on {{ purchase.date_purchased | date:'D F d, Y' }}</li>
        </ol>
    </nav>

    <div class="card my-3" style="max-width: 540px;">
        <div class="row no-gutters">
        <div class="col-md-4">
            <img src="{{ purchase.item.img.url }}" class="card-img" alt="Item Image">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">
                    {{ purchase.item.name }}
                </h5>
                <p class="card-text">{{ purchase.item.description }}</p>
                <p class="card-text"><small class="text-muted">Quantity: {{ purchase.quantity }}</small></p>
                <p class="card-text"><small class="text-muted">Amount: Rs. {{ purchase.purchase_amount | floatformat:'2' }} @ Rs. {{ purchase.item.price | floatformat:'2' }}</small></p>
            
                <a href="{% url 'tracker:purchase-update' purchase.id %}">
                    <i class="fas fa-edit"></i>
                </a>
                |
                <a href="{% url 'tracker:purchase-delete' purchase.id %}">
                    <i class="fas fa-trash"></i>
                </a>
            </div>
        </div>
        </div>
    </div>
{% endblock %}

tracker/templates/tracker/purchase_form.html
{% extends "tracker/base.html" %}
{% load crispy_forms_tags %}

{% block body %}
    <nav aria-label="breadcrumb" class="my-3">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'tracker:home' %}">Purchases</a></li>
            <li class="breadcrumb-item active" aria-current="page">Add Purchases</li>
        </ol>
    </nav>

    <div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class = "border-bottom mb-4">Add Purchases</legend>
                {{ form | crispy }}
            </fieldset>
            <div class = "form-group">
                <button class = "btn btn-success" type = "submit">Update</button>
            </div>
        </form>
    </div>
{% endblock body %}